Добавляет детальные требования к фронтенд разработчикам начального уровня, разбитые по группам компетенций
physcodestyle/roadmap pull request #5
Opened 2024-07-08 17:54 UTC by denisputnov

2024-07-09 14:02 UTC, igsekor commented
PR не совсем в ту ветку 😇

2025-03-17 12:40 UTC, igsekor requested changes
В целом неплохо, но, кажется, надо бы ещё пару идей отработать

2025-03-17 12:40 UTC, igsekor commented on README.md
> +Эта дорожная карта содержит список знаний, умений и навыков, необходимых FrontEnd-разработчику на начальном этапе карьеры. Кривая обучения разбита по технологическим зонам на основе опыта работы учас
```suggestion
Эта дорожная карта содержит список знаний, умений и навыков, необходимых Frontend-разработчику на начальном этапе карьеры. Кривая обучения разбита по технологическим зонам на основе опыта работы участников проекта. Основой для дорожной карты служит список компетенций. Дорожная карта служит ориентиром на пути развития FrontEnd-разработчика.
```

2025-03-17 12:40 UTC, igsekor commented on README.md
> +  - SVG элементы;
```suggestion
  - SVG-элементы;
```

2025-03-17 12:40 UTC, igsekor commented on README.md
> +- Уметь создавать и настраивать формы с использованием тегов `<form>`, `<input>`, `<textarea>`, `<button>`, `<select>`.
Есть мысль добавить сюда ещё теги: `<fieldset>`, `<legend>`, `<label>`

2025-03-17 12:40 UTC, igsekor commented on README.md
> +  - Знать и применять семантические теги (например, `<header>`, `<footer>`, `<section>`, `<article>`, `<nav>`, `<aside>`);
Хорошо бы добавить тег `<main>`

2025-03-17 12:40 UTC, igsekor commented on README.md
> +
Не стоит ли добавить БЭМ и Atomic CSS?

2025-03-17 12:44 UTC, denisputnov commented on README.md
> +
не думаю, что это актуально сейчас

можно добавить, но скорее nice to know а не must have

2025-03-17 12:56 UTC, closed without merging